### ISSUE TITLE
Refine Index Page

### ISSUE THREAD

**Issue by ha-yi** [lombok-android-developer/kotlin-everywhere-mataram-web#2]
Index need to display a landing page with content:

- [x] Change template with a nice one.
- [x] Event name in title: Kotlin/Everywhere & Hacktoberfest Mataram
- [x] List of sponsor with Icons: DigitalOcean, The Dev, Tokopedia, Lumbung Inovasi
- [x] List of support with Icons: Petani Code, Google Developer, IntelliJ,
- [x] Teams: Hayi Nukman, Miftahul Jihad, Khairul Anwar, Mima Amalia, Medicare.
- [x] Speakers: Budi Oktaviyan, Miftahul Jihad, Ari Purnama Aji.
- [x] List of rewards.
- [x] List of Contributors (get from `ContributorHelper.kt`)

**Comment by ha-yi** [comment]
Bounty rewards upon completion of all items in one Pull Request:
- 1x Digital Ocean Shark Squishy
- 1x Hacktoberfest Pin
- 1x Digital Ocean Pin
- Stickers Set (1 Each)

swags only can be claimed on the Kotlin/Everywhere Mataram event in Mataram, Lombok, Indonesia at 26th October 2019.

**Comment by ha-yi** [comment]
Congratulations for @khrlimam Bounty rewards upon completion Pull Request:
1x Digital Ocean Shark Squishy
1x Hacktoberfest Pin
1x Digital Ocean Pin
Stickers Set (1 Each)

swags only can be claimed on the Kotlin/Everywhere Mataram event in Mataram, Lombok, Indonesia at 26th October 2019.

**Comment by khrlimam** [comment]
Thanks TO her <img src="https://lh3.googleusercontent.com/HI8B-5d-Hloy3BSufRDzfcoKKYlBfu2C7rrCa9YgH9LLB9xAWZFP9QcrozVKbBs-sptXgwaRONSKqJIEoACDssgqdmxPcumN1rlHRPJm1P2o4mBHAPDiLSgrdmliASQ3-9TdS2NhM0zGXf441D6VVx8XY26MNxkCjh16A_DUWrnIIQmR1e7ht1U6hmLYegVtUgb6biLJbqsXelOqTyuJFjOnSz_nK3uGSan2sHtfPOtdjf24BlxUX7m6S0wnh7TF3Een0UhIHVT4bOvxzm-7txYDs5ASpTEjLbqwQkeBAneaFR0hFx6zDHIdGjLnYGWxzDPcu-bUah0FXzN-DFyjVh_25RCXlE8UySO5_09s_PTK7Ze3z0qbRxlfhe0xev7kFLaTGGwYfbqN--kP3CPDf48__hWfMTfREyIL3prSidpZGn1klZq04LVF_CotZSvVUFNXBFcMQ1VDzVuQyrNYnlgTPKYgbF9AeY9tF9OnlpbDRMEVmbn_atDn2A_QsjGgwe083ENdX1cSz7MvNSOJ6vkwvU69UJovuy0gLYwwFmvu7_dlmRLXbqnntPIhEhUxXxMkSwmSmQ7WnRUPvRC3pdlMv354U41BzA2N6elt4S-0NS4LXAGv1ZmAVyaWfoycYpi36wKHC1rh5RvTkNDLLydPrczaXYNDOyoOp-YCAMJGYL5XoXMBdVAaWQPvufX7qyvvpeIjWdyB5pqjf2mjIgO9SnmuxzzqrjXz5mGEYnzTOh8=w1082-h1444-no">
