### ISSUE TITLE
Fix static content serving path

### ISSUE THREAD

**Issue by ha-yi** [lombok-android-developer/kotlin-everywhere-mataram-web#3]
Related to #2 

Fix static content serving path. need to use `static` to serve all files under `resources/res`

**Comment by ha-yi** [comment]
bounty reward upon completion:
- 1x Digital Ocean Pin
- Hacktoberfest Pin
- Stickers Set (1x each models)

swags only can be claimed on the Kotlin/Everywhere Mataram event in Mataram, Lombok, Indonesia at 26th October 2019.

**Comment by ha-yi** [comment]
congrats to @khrlimam for bounty PR:
- 1x Digital Ocean Pin
- Hacktoberfest Pin
- Stickers Set (1x each models)

**Comment by khrlimam** [comment]
Yuuuhuuu! thanks! 🦈
